-- MySQL Script generated by MySQL Workbench
-- Sat Feb  5 12:20:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventory_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventory_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventory_management` DEFAULT CHARACTER SET utf8 ;
USE `inventory_management` ;

-- -----------------------------------------------------
-- Table `inventory_management`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `reference` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `weight` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `created_at` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_sales_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `inventory_management`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventory_management`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventory_management`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
